### ISSUE TITLE
TODO bug fixing

### ISSUE THREAD

**Issue by adudzik** [marwin1991/LibamtrackWeb#7]
- [ ] - zeros in logarithmic scale
- [ ] - showing to much data - low performance
- [ ] - special button for deleting all data series - more comfortable
